spring:
  application:
    name: hwhub-batch

  datasource:
    url: jdbc:mysql://localhost:3306/hwhub_db?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Tokyo
    username: hwhub
    password: hwhub
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: NEVER  # Flywayで管理するならnever（後で要調整）

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.hwhub.batch.infrastructure.mybatis.generated.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.hwhub.batch: DEBUG
    org.springframework.batch: INFO
    org.mybatis: DEBUG
#    org.springframework.boot.autoconfigure.batch: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

