spring:
  application:
    name: hwhub-batch
  profiles:
    default: dev

  batch:
    job:
      enabled: false

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.hwhub.batch.infrastructure.mybatis.generated.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    "[com.hwhub.batch]": INFO
    "[org.springframework.batch]": INFO
    "[org.mybatis]": INFO
