spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hwhub_db?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Tokyo
    username: hwhub
    password: hwhub
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.hwhub.batch: DEBUG
    org.mybatis: DEBUG
